### PR TITLE
fix(dns) PG and CASS container aliases on Linux

### PR DESCRIPTION
**Pull request by Apxdono**
A proposed  PR fix for #259 

**Additionally in this PR**

- When I enabled Cassandra, I got a similar error to one I had with Postgres. I went ahead and fixed Cassandra hostname as well
<strike>- Removed `NETWORK_NAME` env variable for 3 simple reasons.
    -  Actual network name is `pongo-test-network` and it's hardcoded in compose file
    - NETWORK_NAME cannot be overridden and doesn't override anything either. It's not used anywhere other than in compose file.
    - If you ever decide to change network name it's much easier to replace the name in one file (Find/Replace, `sed`, what ever...) than to additionally edit `pongo.sh`.</strike>

### CODE REVIEW

**Comment by Tieske** [comment]
`NETWORK_NAME` is used in custom dependencies (actually that is the only reason that variable exists). See how it is used here; https://github.com/Kong/kong-pongo#custom-local-dependencies

**Comment by Apxdono** [comment]
Guess I was a bit trigger happy with this one then. I'll add it back. Do you want to still use this variable in a compose file?

**Comment by Tieske** [comment]
I push another commit on your branch. Lining up the other containers as well useing the same names. And when going this route, there is no need to retain the "_1" postfixes, right?

wdyt @Apxdono ?

**Comment by Tieske** [comment]
> Do you want to still use this variable in a compose file?

No need in the compose file, but the variable needs to exist for backward compatibility, since other compose snippets might be depending on it

**Comment by Apxdono** [comment]
@Tieske Agree, `_1` is redundant since this PR basically redefines container naming.

**Pull request merged**
