### PR TITLE
feat(conf) add the ability to specify KONG_DATABASE configuration

### PR DESCRIPTION
**Pull request by mikefero**

### CODE REVIEW

**Comment by Tieske** [comment]
@mikefero @hutchic I don't think this is the right approach. The test file should specify what it is running, this shouldn't be in Pongo. In the test file you can specify the environment variable to start Kong with a specific database.

**Comment by mikefero** [comment]
> In the test file you can specify the environment variable to start Kong with a specific database.

Don't disagree with you there. Let me think on a different solution for testing plugins using dbless mode.

**Comment by Tieske** [comment]
we should probably update the example/template plugin to show how it's done: https://github.com/Kong/kong-plugin

**Comment by Elyahou** [comment]
@Tieske Can you please provide more information on how to specify database, for excluding for example `cassandra` strategy when running test ?

**Comment by mikefero** [comment]
@Elyahou To exclude `Apache Cassandra` from starting you can update your `.pongorc` to include `--no-cassandra`; see [test dependencies ](https://github.com/Kong/kong-pongo#test-dependencies) section of the README. Then instead of using the `helper` to go over each strategy allowable by Kong you can just set `database = "postgres"` when you call `helpers.start_kong()`.

Example:

```
assert(helpers.start_kong({
  database = "postgres",
  plugins = "bundled,<name-of-custom-plugin>",
  nginx_conf = "spec/fixtures/custom_nginx.template",
}))
```

**Comment by Tieske** [comment]
I think in general it is good practice to test against both datastores. That said, Cassandra can slow down the tests when you're developing. To disable running the tests each time try this:

```shell
pongo run -- --exclude-tags=cassandra
```

The datastore names are inserted as 'tags' in the tests, and by using the busted commandline option `--exclude-tags` you can have them skipped.

**Pull request closed without merging**
