### PR TITLE
feat(version) added Kong Enterprise version 2.2.1.6

### PR DESCRIPTION
**Pull request by tyler-ball**

### CODE REVIEW

**Comment by Tieske** [comment]
@tyler-ball something went wrong here. It has a merg econflict, but also I only see 1 commit? there should be two, 1 the update, 2 the artifacts.

Any idea what happened?

**Comment by Tieske** [comment]
also 2.2.1.2 was the last in the 2.2. series, now there is 2.2.1.6? what happened to the versions in between?

**Comment by Tieske** [comment]
ping @tyler-ball

**Comment by tyler-ball** [comment]
@Tieske I have no idea, closing this

**Pull request closed without merging**
