### PR TITLE
fix(*) delete the bytecode of target plugin

### PR DESCRIPTION
**Pull request by ADD-SP**

### CODE REVIEW

**Review by fffonion — APPROVED** [review]

**Comment by Tieske** [comment]
This is not ok imo. We should change the Kong package such that .Lua files have precedence over the .ljbc files. 

This is not only important for Pongo but also for support. We often ship modified files for troubleshooting and debugging, and this will cause trouble every time. 

Ping @RobSerafini

**Comment by Tieske** [comment]
Link to internal discussion: https://kongstrong.slack.com/archives/C02GZ0CGJNT/p1652975720927929

**Comment by ADD-SP** [comment]
@Tieske But it makes our CI not reliable, I think we can merge this PR, and revert it after we address this issue elegantly.

**Comment by outsinre** [comment]
My PR with EE plugin `opa` is blocked for 2 months due to this issue: https://github.com/Kong/kong-ee/pull/3271.

I tested it locally with Pongo, it's ok.

**Comment by fffonion** [comment]
@Tieske I have asked Qiqi to take a look at kbt for a proper fix moving forward, for now let's merge in this PR to unblock team that working on plugin fixes.

**Comment by Tieske** [comment]
The fix should be in Kong, not Pongo. Pongo supports all Kong versions all the way back to Kong 0.13.0. If we merge it in Pongo, then there is no removing it later. Because of all the old versions supported.

The build update (everything compiled to bytecode) is an update for 3.0, so that is on the `master` branch only. So there are 2 options;

1. fix it in Pongo, meaning;
    - fix in in Pongo (this PR)
    - fix it in Kong, before 3.0 is released
    - revert the fix in Pongo

2. fix it in Kong, before 3.0 is released.

I don't see in what scenario we'd choose option 1 over option 2?

**Comment by fffonion** [comment]
I understand the concern of "proper fix" here, but I don't see any risk of this change in pongo (if there's one I missed, please let me know). On versions that those bytecode are not exist, this change becomes a no-op.

Option 2 means more complicated fix and test, we will not be able to merge any ee plugin related PR during this, it will either fail or report false positive.

If we really concerned about maintaining backward compatibility at pongo master branch, maybe we should start a 3.0 branch for pongo just to unblock 3.0 development works, while the proper fix in packaging are being fixed.

**Comment by Tieske** [comment]
If a 3.0 branch works, then you can already use is pr’s branch to get around the issues? That’s fine I think. 

Just make sure the Kong packaging fix gets into 3.0

**Comment by tyler-ball** [comment]
I just merged https://github.com/Kong/kong-ee/commit/626764806ec044ba6d9bded5c02e81ac18517e19 to master, referencing this Pongo branch. I'm going to add a comment to FT-3181 to revert that when a proper fix is introduced

**Comment by Tieske** [comment]
Can we close this PR?

**Comment by tyler-ball** [comment]
Restoring this branch until https://github.com/Kong/kong-ee/pull/3589 is fixed and merged

**Comment by Tieske** [comment]
@ADD-SP do we still need this branch around? the PR @tyler-ball mentioned has been merged a month ago?

**Pull request closed without merging**
