### PR TITLE
feat(shell) allow specifying script file with @

### PR DESCRIPTION
**Pull request by Tieske**

### CODE REVIEW

**Comment by Tieske** [comment]
@hutchic the idea of this PR is to be able to run CI scripts inside the generated test images for validation purposes (Pongo's own CI that is)

**Comment by kidd** [comment]
gojira uses `@` for a slightly different thing.  wouldn't `run` be able to do the same (maybe with some quote and flag juggling)?

**Comment by Tieske** [comment]
`run` runs the tests, `shell` gives a shell (interactive), `shell some command` simply executes `some command`.

It is exactly the whole quoting thing that makes it such a hassle, hence `shell @scriptfile` (stolen from curl/httpie) to skip on all the escaping. Adding more flags also seems like a hassle...

**Comment by kidd** [comment]
just wanted to note it, I'm cool with @file also.

**Pull request merged**
