### PR TITLE
test(redis-cluster) fti-2014 test

### PR DESCRIPTION
**Pull request by outsinre**
Only for test purpose. Don't merge.

### CODE REVIEW

**Comment by Tieske** [comment]
@outsinre FYI: there's a travis run, so it seems your base branch it outdated.

**Comment by outsinre** [comment]
> @outsinre FYI: there's a travis run, so it seems your base branch it outdated.

My branch is based on `1.3.0` to keep compatible with current `kong-ee` master. Should I rebase?

**Comment by Tieske** [comment]
Pongo 2 is be compatible with Kong 3+, so I think it should be rebased indeed

**Comment by outsinre** [comment]
> 



> Pongo 2 is be compatible with Kong 3+, so I think it should be rebased indeed

Got it. So I will use the master branch as it already includes the changes.

**Pull request closed without merging**
