### PR TITLE
chore(test): change some methods to public and add portal conf into nginx.conf template

### PR DESCRIPTION
**Pull request by raoxiaoyan**
1. Make some methods for the public. 
2. Add portal conf into `custom_nginx.template`.
It fixes this PR test case which backports from the master branch. https://github.com/Kong/kong-ee/pull/4759

### CODE REVIEW

**Review by Tieske — COMMENTED** [review]
The changed files in this PR are all files that originate from the Kong EE repo. They should not be changed here, on a next release they will be regenerated and hence be overwritten again.

**Comment by raoxiaoyan** [comment]
> The changed files in this PR are all files that originate from the Kong EE repo. They should not be changed here, on a next release they will be regenerated and hence be overwritten again.

How can I make this PR test case all green? https://github.com/Kong/kong-ee/pull/4759

**Comment by kikito** [comment]
(reopening for continuing the discussion)

I believe we have here is a fix that needs to be backported (and tested) to older versions of Kong (notice that the pr is against 3.0.x.x).
* The backported fix includes changes
* The backported fix uses Pongo for the tests
* Pongo has a "cache" of kong 3.0.x.x (inside `kong-versions`).
* The fixes fail on that branch because Pongo's "cache" doesn't have those changes, and it is waiting for a release.

But we currently don't have a release scheduled for 3.0.x.x. We are backporting a fix to 3.0.x.x *just in case* we need to release 3.0.x.x in the future, because of a security vulnerability, for example.

How would we solve this deadlock? Would it be acceptable to create a "fake kong-ee" (`3.0.2.1`) instead?

**Comment by Tieske** [comment]
That's gonna be very brittle most likely.

How about we rename this branch (the branch this PR is from) to `backport/3.0.x.x`. And then in the Kong-EE repo point the CI to use this Pongo branch. And then mark this PR as "draft" and "do-not-merge", to prevent accidental merges in Pongo.

Hopefully the work @fffonion did to test against the checkedout EE source will prevent issues like this in the future. For the 2.8.x.x LTS versions we can create a separate Pongo maintenance branch.

**Comment by Tieske** [comment]
see https://github.com/Kong/kong-ee/pull/4759#issuecomment-1505042234

closing this

**Pull request closed without merging**
