### PR TITLE
feat(version) added Kong open source version 2.5.1

### PR DESCRIPTION
**Pull request by mashapedeployment**

### CODE REVIEW

**Comment by Tieske** [comment]
@gszr @hutchic this image is based on Alpine 3.14.2, and hence is broken on the permissions error again.

What I do not get is how that happened? in `docker-kong` we still have [the PR pending to update it](https://github.com/Kong/docker-kong/pull/495), right? Then how come we generated this image?

**Comment by Tieske** [comment]
fyi, the image pulled is the unofficial one still from our own repo, not the official docker one, so probably we can update it still?

**Comment by Tieske** [comment]
I tested locally, using docker `20.10.8` and then it works;
```shell
thijss-macbook:kong-pongo thijs$ docker -v
Docker version 20.10.8, build 3967b7d
thijss-macbook:kong-pongo thijs$ pongo shell
Error response from daemon: manifest for kong:2.5.1-alpine not found: manifest unknown: manifest unknown
[pongo-WARN] failed to pull image kong:2.5.1-alpine.
[pongo-INFO] failed to pull: kong:2.5.1-alpine from the official repo, retrying unofficial...
2.5.1: Pulling from kong/kong
Digest: sha256:6f1ade744464ee261cc087dc63c89b47d9121111b8902f9ebbad499d2585dd15
Status: Image is up to date for kong/kong:2.5.1
docker.io/kong/kong:2.5.1
[pongo-INFO] pulling unofficial image succeeded
Creating kong-pongo_kong_run ... done
Kong version: 2.5.1
[Kong-2.5.1:/kong]#
```

In CI the docker version is [`18.06.0`](https://app.travis-ci.com/github/Kong/kong-pongo/jobs/536054686#L31-L33).

According to [the report](https://github.com/alpinelinux/docker-alpine/issues/146#issuecomment-869595012) version `20.10.0` fixes the issue, and it was [released 8-Dec-2020](https://docs.docker.com/engine/release-notes/#20100).

So I see 2 problems here:
1. why was this image even created with `3.14` if we haven't upgraded the docker files yet?
2. when/how do we make the new docker version available everywhere, so we can switch to newer Alpine images

Number 2 above is hard, just updating Docker in this Pongo repo in CI is easy, but everywhere Pongo runs in CI (which is at least in all of our plugins, and many users plugin repos) it will probably start to fail the moment we'd merge it.

**Comment by gszr** [comment]
> @gszr @hutchic this image is based on Alpine 3.14.2, and hence is broken on the permissions error again.
> 
> What I do not get is how that happened? in `docker-kong` we still have [the PR pending to update it](https://github.com/Kong/docker-kong/pull/495), right? Then how come we generated this image?

I think the `alpine` build step also pushes an image. We pinned the version in the "release per commit" job, but not in the packaging job. PR: https://github.com/Kong/kong/pull/7820

**Comment by gszr** [comment]
Once that PR is merged and "release per commit" runs, the latest tag will be updated, fixing the issue.

**Comment by hutchic** [comment]
> 1. why was this image even created with 3.14 if we haven't upgraded the docker files yet?

a side goal of the nightlies was to validate against the bleeding edge which is why we historically haven't explicitely pinned the base images of alpine/ubuntu/centos. This bug getting caught is good the way it was caught is what's not ideal

> 2. when/how do we make the new docker version available everywhere, so we can switch to newer Alpine images

up for PR https://github.com/Kong/kong-pongo/pull/205

**Comment by Tieske** [comment]
rebased on `master` and force-pushed to re-run CI with the new ubuntu version specified in travis.yml.

**Pull request merged**
