### PR TITLE
support to globally disable health checks

### PR DESCRIPTION
**Pull request by Tieske**
replaces #404

### CODE REVIEW

**Comment by Tieske** [comment]
Weird CI errors;
```

Successfully tagged kong-pongo-test:2.0.5
[pongo-INFO] image 'kong-pongo-test:2.0.5' successfully build
Service "expose" defines an invalid healthcheck: "disable: true" cannot be combined with other options
Pongo test suite [ failed  ] build image: builds the specified image: 2.0.5
Pongo test suite [  start  ] build image: patch release is resolved: 2.0.x
[pongo-INFO] image 'kong-pongo-test:2.0.5' already exists
[pongo-INFO] Resolved Kong version '2.0.x' to '2.0.5'
Service "expose" defines an invalid healthcheck: "disable: true" cannot be combined with other options
Pongo test suite [ failed  ] build image: patch release is resolved: 2.0.x
Pongo test suite [  start  ] build image: bad version fails with error
```
Any ideas @onmomo ?

**Comment by Tieske** [comment]
it preferred the old `docker-compose` (separate binary), over `docker compose` (`compose` within the `docker` binary), so changing that solved the issue in CI. But I'm not convinced this is right, will it break some peoples setup?

I tried locally with both binaries, and it didn't fail for me. So maybe in CI the `docker-compose` is just too old...

**Comment by onmomo** [comment]
> it preferred the old `docker-compose` (separate binary), over `docker compose` (`compose` within the `docker` binary), so changing that solved the issue in CI. But I'm not convinced this is right, will it break some peoples setup?
> 
> I tried locally with both binaries, and it didn't fail for me. So maybe in CI the `docker-compose` is just too old...

@Tieske 
Actually, I would vote to completely drop docker-compose v1 from `pongo.sh` now or very soon. The tools diverged quite a bit. eg (docker-compose --version vs docker compose version) and as I understand the docs, docker-compose v1 is no longer maintained and they will stop distributing it with Docker Desktop after June 2023.
* https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose

**Comment by Tieske** [comment]
I get that (docker-compose being deprecated et all), but my worry is with the breaking change this might be for some folks.

**Comment by Tieske** [comment]
@curiositycasualty any opinions on this?

**Comment by curiositycasualty** [comment]
> @curiositycasualty any opinions on this?

This PR's changes seem fine.

And I think dropping support for docker-compose v1 should be already.
Maybe add a warning message so that if pongo stops working for folks because of deprecating docker-compose v1, they can have some indication as to why.

**Review by hanshuebner — APPROVED** [review]

**Pull request merged**
