### PR TITLE
feat(kong-ce) dynamically fetches kong ce version tags

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Core team doesn't want to update versions manually, so we automated that on Pongo.

### CODE REVIEW

**Comment by bungle** [comment]
> Also, the way it is implemented means that on every "pongo" command the repo is going to be cloned.

No:

as soon as you have `if [ ! -f "${LOCAL_PATH}/.kong-ce" ]; then` aka after first run, we will not clone anything.

**Comment by bungle** [comment]
@Tieske the PR is now updated with removal of `mapfile`, it should now work with bash that does not have that.

**Comment by bungle** [comment]
> if will not be able to run while "off-line" (this includes corporate environments with network, but without github access)

It runs just fine offline, provided that you have run it once online.

**Comment by bungle** [comment]
@Tieske and I btw. implemented `KONG_CE_VERSIONS_EXCLUDE` too.

**Comment by Tieske** [comment]
closing this, considering https://github.com/Kong/kong/pull/5709

**Pull request closed without merging**
